# Generated by Django 5.2.6 on 2025-09-05 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Maker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Chassis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                (
                    "maker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chassis_codes",
                        to="pricepred.maker",
                    ),
                ),
            ],
            options={"unique_together": {("maker", "code")},},
        ),
        migrations.CreateModel(
            name="CarSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auction_house", models.CharField(blank=True, max_length=100)),
                ("auction_date", models.DateField()),
                ("year", models.IntegerField()),
                ("mileage", models.IntegerField(help_text="in km")),
                ("color", models.CharField(max_length=30)),
                ("auction_grade", models.CharField(max_length=5)),
                ("interior_grade", models.CharField(max_length=2)),
                ("exterior_grade", models.CharField(blank=True, max_length=2)),
                (
                    "start_price",
                    models.IntegerField(
                        blank=True, help_text="Starting price in JPY", null=True
                    ),
                ),
                (
                    "final_price",
                    models.IntegerField(help_text="Final hammer price in JPY"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chassis_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pricepred.chassis",
                    ),
                ),
                (
                    "maker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pricepred.maker",
                    ),
                ),
            ],
        ),
    ]
