# Generated by Django 5.2.6 on 2025-09-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricepred", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carsale",
            name="auction_grade",
            field=models.CharField(
                choices=[
                    ("S", "S"),
                    ("6", "6"),
                    ("5", "5"),
                    ("4.5", "4.5"),
                    ("4", "4"),
                    ("3.5", "3.5"),
                    ("3", "3"),
                    ("2", "2"),
                    ("1", "1"),
                    ("RA", "RA"),
                    ("R", "R"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="carsale",
            name="color",
            field=models.CharField(
                choices=[
                    ("White", "White"),
                    ("Black", "Black"),
                    ("Silver", "Silver"),
                    ("Gray", "Gray"),
                    ("Blue", "Blue"),
                    ("Red", "Red"),
                    ("Other", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="carsale",
            name="exterior_grade",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D"), ("E", "E")],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="carsale",
            name="interior_grade",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D"), ("E", "E")],
                max_length=2,
            ),
        ),
    ]
