# Generated by Django 5.2.6 on 2025-09-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricepred", "0002_alter_carsale_auction_grade_alter_carsale_color_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="chassis", unique_together=set(),),
        migrations.AddField(
            model_name="chassis",
            name="variant",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="chassis", unique_together={("maker", "code", "variant")},
        ),
    ]
