# Generated by Django 5.2.6 on 2025-12-12 14:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricepred", "0003_alter_chassis_unique_together_chassis_variant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carsale",
            name="auction_date",
            field=models.DateField(help_text="Date of the auction."),
        ),
        migrations.AlterField(
            model_name="carsale",
            name="auction_grade",
            field=models.CharField(
                choices=[
                    ("S", "S"),
                    ("6", "6"),
                    ("5", "5"),
                    ("4.5", "4.5"),
                    ("4", "4"),
                    ("3.5", "3.5"),
                    ("3", "3"),
                    ("2", "2"),
                    ("1", "1"),
                    ("RA", "RA"),
                    ("R", "R"),
                ],
                help_text="Overall auction grade.",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="carsale",
            name="auction_house",
            field=models.CharField(
                blank=True,
                help_text="Name of the auction house (e.g. USS Tokyo).",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="carsale",
            name="chassis_code",
            field=models.ForeignKey(
                help_text="Chassis / platform code for this vehicle.",
                on_delete=django.db.models.deletion.PROTECT,
                to="pricepred.chassis",
            ),
        ),
        migrations.AlterField(
            model_name="carsale",
            name="color",
            field=models.CharField(
                choices=[
                    ("White", "White"),
                    ("Black", "Black"),
                    ("Silver", "Silver"),
                    ("Gray", "Gray"),
                    ("Blue", "Blue"),
                    ("Red", "Red"),
                    ("Other", "Other"),
                ],
                help_text="Normalised exterior colour.",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="carsale",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when this record was created."
            ),
        ),
        migrations.AlterField(
            model_name="carsale",
            name="exterior_grade",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D"), ("E", "E")],
                help_text="Exterior condition grade (optional).",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="carsale",
            name="final_price",
            field=models.IntegerField(
                help_text="Final hammer price in JPY.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="carsale",
            name="interior_grade",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D"), ("E", "E")],
                help_text="Interior condition grade.",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="carsale",
            name="maker",
            field=models.ForeignKey(
                help_text="Vehicle manufacturer.",
                on_delete=django.db.models.deletion.PROTECT,
                to="pricepred.maker",
            ),
        ),
        migrations.AlterField(
            model_name="carsale",
            name="mileage",
            field=models.IntegerField(
                help_text="Odometer reading in kilometres.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="carsale",
            name="start_price",
            field=models.IntegerField(
                blank=True,
                help_text="Starting price in JPY (if available).",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="carsale",
            name="year",
            field=models.IntegerField(
                help_text="Model year (Gregorian calendar).",
                validators=[
                    django.core.validators.MinValueValidator(1980),
                    django.core.validators.MaxValueValidator(2100),
                ],
            ),
        ),
    ]
